version: '3'

services:
  app:
    build: bot/
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: 'weather'
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_ROOT_PASSWORD: 27122000
    ports:
      - 3306:3306
    volumes:
      - .data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080