version: '3'

services:
  app:
    build: bot/
    ports:
    - 8000:8000
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: 'weather'
      MYSQL_ROOT_PASSWORD: 27122000
    ports:
      - 8001:5432
    volumes:
      - .data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
